# Generated by Django 4.0.5 on 2022-06-17 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Contact_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(default='user', max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Discription', models.TextField()),
            ],
        ),
    ]
