# Generated by Django 4.0.5 on 2022-06-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Date_Created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='Time_Created',
            field=models.TimeField(auto_now=True),
        ),
    ]
