# Generated by Django 4.0.5 on 2022-06-27 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact_date_created_contact_time_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Country', models.CharField(default='', max_length=50)),
                ('Address', models.TextField()),
                ('City', models.CharField(default='', max_length=50)),
                ('State', models.CharField(default='', max_length=50)),
                ('Zip', models.IntegerField()),
                ('Json_Data', models.TextField()),
            ],
        ),
    ]
