# Generated by Django 4.0.5 on 2022-06-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_date_ordered_order_time_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('Processing', 'PR'), ('Shipped', 'SH'), ('In Transit', 'IT'), ('Out For Delivery', 'OFD'), ('Delivered', 'SUC')], default='Processing', max_length=20)),
                ('Discription', models.TextField(default='In Processing......')),
                ('Tracking_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
    ]
