# Generated by Django 4.0.5 on 2022-07-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Status',
            field=models.CharField(choices=[('Processing', 'PROCESSING'), ('Shipped', 'SHIPPING'), ('In Transit', 'IN_TRANSIT'), ('Out For Delivery', 'OUT_FOR_DELIVERY'), ('Delivered', 'DELIVERED')], default='Processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Tracking_Id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
